### ISSUE TITLE
Unable to list down events

### ISSUE THREAD

**Issue by sukumarp2020** [sensu/sensu-go-python#21]
I'm trying to communicate with sensu API and list down events.
I was able to list down the checks and assets. But getting 404 error.

When I try `list(client.events.list())`

I'm getting below error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sensu_go/clients/resource/base.py", line 43, in __iter__
    raise ResponseError(
sensu_go.errors.ResponseError: Expected 200 when listing resources:
  URL: <sensu_api_url>
  status: 404
  text: {"code":2,"message":"not found"}
```

**Comment by tadeboro** [comment]
Hi, @sukumarp2020. Can you please post the path and query part of the URL so that we can determine the API endpoint that returned back 404? It looks like the API endpoint you are trying to reach is `GET /api/core/v2/namespaces/default/events` and that endpoint should never return back 404, but without the path and query, we cannot be sure.

**Comment by sukumarp2020** [comment]
> Hi, @sukumarp2020. Can you please post the path and query part of the URL so that we can determine the API endpoint that returned back 404? It looks like the API endpoint you are trying to reach is `GET /api/core/v2/namespaces/default/events` and that endpoint should never return back 404, but without the path and query, we cannot be sure.

Thanks for the quick response. 
Here's the endpoint it's trying to get. 

`/api/core/v2/namespaces/mongodb/events?limit=100`

I do have the mongodb namespace.

**Comment by tadeboro** [comment]
Hmm, the `GET /api/core/v2/namespaces/<namespace>/events` does not [document return status 404](https://docs.sensu.io/sensu-go/latest/api/events/#events-get-specification). And I cannot replicate the behavior locally here (

Does the user that you are using to manage Sensu Go have enough permissions on the MongoDB namespace? RBAC often returns 404 when the access was denied in order not to disclose information to unauthorized users.

**Comment by sukumarp2020** [comment]
Yes. The user does have admin permissions and I was able to view the events in sensu dashboard. 
I was able to list down the checks as well. The issues exists only with **events**.

**Comment by tadeboro** [comment]
That is strange. Does this bash script also return 404 on your machine? You will need to update the `api`, `username`, and `password` variables to match your environment.

```bash
#!/bin/bash

set -euo pipefail

readonly api="http://localhost:8080"
readonly username="admin"
readonly password="P@ssw0rd!"

readonly token=$( \
  curl -s -u "${username}:${password}" "${api}/auth" \
  | jq -r ".access_token" \
)

curl -v -s -H "Authorization: Bearer $token" \
  "${api}/api/core/v2/namespaces/mongodb/events?limit=100" > /dev/null
```

When I run this script against a fresh Sensu Go instance running in docker, I get back status 200 even if the `mongodb` namespace does not exist.

**Comment by sukumarp2020** [comment]
I'm getting 400 Bad Request when running this script.

**Comment by tadeboro** [comment]
What version of sensu Go are you using? I tested the script against the official docker image.

**Comment by sukumarp2020** [comment]
It's **5.20.2**

**Comment by tadeboro** [comment]
I cannot replicate this. What I did to test this out is:

 1. Run `docker run --rm -p 8080:8080 -p 3000:3000 sensu/sensu:5.20.2 sensu-backend start` on one terminal.
 2. Run the bash script that I posted previously (without any changes since, by default, docker images use credentials that I listed in the script).

What I get back is this:

```
$ bash test.sh 
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /api/core/v2/namespaces/mongodb/events?limit=100 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.71.1
> Accept: */*
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjYyNDg2ODQsImp0aSI6ImZiN2QxYjY0ZTNmNDJhOWJiM2RlZDZhNWU1YTU5MTBjIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwic3ViIjoiYWRtaW4iLCJncm91cHMiOlsiY2x1c3Rlci1hZG1pbnMiLCJzeXN0ZW06dXNlcnMiXSwicHJvdmlkZXIiOnsicHJvdmlkZXJfaWQiOiJiYXNpYyIsInByb3ZpZGVyX3R5cGUiOiIiLCJ1c2VyX2lkIjoiYWRtaW4ifSwiYXBpX2tleSI6ZmFsc2V9.R23LdnIie72iKgYV28_zH47epx6edwZ9yrSvOHB98b4
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Sensu-Entity-Count: 0
< Sensu-Entity-Limit: 100
< Sensu-Entity-Warning: 
< Date: Wed, 14 Jul 2021 07:39:44 GMT
< Content-Length: 2
< 
{ [2 bytes data]
* Connection #0 to host localhost left intact
```

Note: Sensu Go versions 5.x are not supported anymore. See https://docs.sensu.io/sensu-go/latest/versions/ for the list of supported versions.
